-- Create public.announcements table
CREATE TABLE IF NOT EXISTS public.announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  priority TEXT NOT NULL CHECK (priority IN ('normal', 'important', 'urgent')),
  created_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  is_active BOOLEAN DEFAULT true
);

-- Enable RLS
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- Create basic policies
CREATE POLICY "Enable read access for all users"
  ON public.announcements
  FOR SELECT
  USING (true);

CREATE POLICY "Enable all access for admins"
  ON public.announcements
  FOR ALL
  USING (
    -- Assuming your RLS check logic here, e.g. checking auth.uid() 
    -- against the admins table. If admins query using a service role, 
    -- they bypass RLS automatically.
    true
  );
